openapi: 3.1.0
info:
  title: 1Link IBFT Push
  description: 1Link IBFT Push
  version: 1.0.0
paths:
  /1Link/title/fetch:
    post:
      summary: 1Link IBFT Push
      description: 1Link IBFT Push
      requestBody:
        description: 1Link IBFT Push
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IBFTRequestBody'
        required: true
      responses:
        '201':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IBFTResponseBody'
              examples:
                laurent_307:
                  summary: Creation of a valid car response
                  value:
                    ResponseCode: '00'
                    PAN: '998876000000024424'
                    Amount: '000000100000'
                    TransmissionDateAndTime: '1015133513'
                    STAN: '102045'
                    TimeLocalTransaction: '133513'
                    DateLocalTransaction: '1015'
                    DateSettlement: 0428
                    RRN: '000000024424'
                    AuthorizationIdentificationResponse: '102043'
                    ToBankIMD: '199667'
                    AccountNumberTo: '6304532132598659'
                    Reserved1: Reserved
                    Reserved2: Reserved
                    Reserved3: Reserved
                    ResponseDetail: PROCESSED OK
components:
  schemas:
    IBFTResponseBody:
      type: object
      properties:
        ResponseCode:
          type: string
          example: '00'
        PAN:
          type: string
          example: '998876000000024424'
        Amount:
          type: string
          example: '000000100000'
        TransmissionDateAndTime:
          type: string
          example: '1015133513'
        STAN:
          type: string
          example: '102045'
        TimeLocalTransaction:
          type: string
          example: '133513'
        DateLocalTransaction:
          type: string
          example: '1015'
        DateSettlement:
          type: string
          example: 0428
        RRN:
          type: string
          example: '000000024424'
        AuthorizationIdentificationResponse:
          type: string
          example: '102043'
        ToBankIMD:
          type: string
          example: '199667'
        AccountNumberTo:
          type: string
          example: '6304532132598659'
        Reserved1:
          type: string
          example: Reserved
        Reserved2:
          type: string
          example: Reserved
        Reserved3:
          type: string
          example: Reserved
        ResponseDetail:
          type: string
          example: PROCESSED OK
      additionalProperties: false
    IBFTRequestBody:
      type: object
      properties:
        TransactionAmount:
          maxLength: 12
          minLength: 1
          type: string
          description: |-
            Transaction amount in PKR, up to 2 
            decimal places
          example: '000000100000'
        TransmissionDateAndTime:
          maxLength: 10
          minLength: 1
          type: string
          description: |-
            Transmission date and time, Format: 
            “MMDDhhmmss”.
          example: '1015133513'
        STAN:
          maxLength: 6
          minLength: 1
          type: string
          description: |
            System Trace Audit Number.
          example: '102045'
        Time:
          maxLength: 6
          minLength: 1
          type: string
          description: |-
            Local transaction time,
            Format: “hhmmss”
          example: '133513'
        Date:
          maxLength: 4
          minLength: 1
          type: string
          description: |
            Local transaction date. 
            Format: “MMDD”
          example: '1015'
        MerchantType:
          maxLength: 4
          minLength: 1
          type: string
          description: |-
            Four-digit code identifying 
            merchant.
          example: '0003'
        FromBankIMD:
          maxLength: 11
          minLength: 1
          type: string
          description: |
            The bank IMD/BIN of acquiring bank.
          example: '998876'
        RRN:
          maxLength: 12
          minLength: 1
          type: string
          description: Reference number sent by the acquirer.
          example: '000000024424'
        AuthorizationIdentificationResponse:
          maxLength: 6
          minLength: 1
          type: string
          description: |-
            6-digit Authorization Identification 
            Response is a code generated by 
            an issuer for transactions 
            authorized by the issuer.
          example: '102043'
        CardAcceptorTerminalId:
          maxLength: 8
          minLength: 1
          type: string
          description: |-
            Unique requesting terminal 
            identifier.
          example: '40260275'
        CardAcceptorIdCode:
          maxLength: 15
          minLength: 1
          type: string
          description: |-
            Code uniquely identifying card 
            acceptor.
          example: '402626030259047'
        MerchantDetail:
          maxLength: 999
          type: string
          description: |-
            In transactions this field contains 
            Merchant Category code
          example: ''
        PaymentDetail:
          maxLength: 44
          minLength: 1
          type: string
          description: |-
            Issuing transactions this field 
            contains Merchant Category code 
            Payment Code (length=4) 
            Payment Details (length=40)
          example: 0320 Donations  Charity
        CurrencyCodeTransaction:
          maxLength: 3
          minLength: 1
          type: string
          description: |-
            Currency Code, Transaction is the 
            local currency of the acquirer.
          example: '586'
        AccountNumberFrom:
          maxLength: 28
          minLength: 1
          type: string
          description: |-
            AccountNumberFrom is a 
            digits/characters used to 
            identify customer account
          example: '3528555323354910'
        AccountNumberTo:
          maxLength: 28
          minLength: 1
          type: string
          description: |-
            This field contains Destination 
            Account Number
          example: '6304532132598659'
        ToBankIMD:
          maxLength: 11
          minLength: 1
          type: string
          description: |-
            The bank IMD/BIN of 
            issuer bank
          example: '221166'
        PAN:
          maxLength: 19
          type: string
          description: |
            Personal Account Number.
          example: '4250108749566'
        ExpiryDate:
          maxLength: 4
          minLength: 1
          type: string
          example: '2812'
        PosEntryMode:
          maxLength: 3
          minLength: 1
          type: string
          description: |
            Point-of-Service Entry Mode
          example: '021'
        BeneficiaryBankName:
          maxLength: 20
          type: string
          description: |-
            This field will contain the Bank Name 
            of “To/Destination” Account
          example: Allied Bank
        Reserved1:
          maxLength: 999
          type: string
          description: |-
            Reserved for future 
            use.
          example: Reserved
        Reserved2:
          maxLength: 999
          type: string
          description: |-
            Reserved for future 
            use.
          example: Reserved
        Reserved3:
          maxLength: 999
          type: string
          description: |-
            Reserved for future 
            use.
          example: Reserved
        RTPID:
          maxLength: 30
          minLength: 1
          type: string
          description: |
            1RTP ID generated against payment.
        ReferenceNo:
          maxLength: 24
          minLength: 1
          type: string
          description: |
            Reference no against 1RTP.
        SenderName:
          maxLength: 30
          minLength: 1
          type: string
          description: |-
            This field contains name of sender 
            who is sending funds.
        SenderIBAN:
          maxLength: 25
          minLength: 1
          type: string
          description: |-
            This field contains IBAN or Mobile 
            Account Number
      additionalProperties: false
