openapi: 3.1.0
info:
  title: 1Link Title Fetch
  description: 1Link Title Fetch
  version: 1.0.0
paths:
  /1Link/title/fetch:
    post:
      summary: 1Link Title Fetch
      description: 1Link Title Fetch
      requestBody:
        description: 1Link Title Fetch
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/titleFetchRequestBody'
        required: true
      responses:
        '201':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/titleFetchRep'
              examples:
                title_fetch:
                  summary: Creation of a valid car response
                  value: >-
                    { "ResponseCode": "vazadwiju", "Pan": "elepore", "Amount":
                    "6422368559824896", "TransmissionDateAndTime": "11/30/2077",
                    "Stan": "wepdutafjiklisin", "TimeLocalTransaction": "19:46",
                    "DateLocalTransaction": "4/1/2049", "DateSettlement":
                    "8/19/2047", "RetrievalReferenceNumber": "5149289997139968",
                    "AuthorizationIdentificationResponse": "3187567019163648",
                    "accountNumberTo": "5433014307501764", "Alias":
                    "vewdufokcozacov", "ToBankImd": "ifuehituaberezo",
                    "accountTitleTo": "4026963071924808", "branchNameTo":
                    "Richard Knight", "BankName": "Ophelia Figueroa",
                    "IBAN_MobileAccountNumber": "36670454669977", "Reserved1":
                    "riblipurneib", "Reserved2": "jesd", "Reserved3":
                    "hilenefizano", "ResponseDetail": "eniwopuodtahwo" }
components:
  schemas:
    titleFetchRequestBody:
      type: object
      properties:
        TransactionAmount:
          maxLength: 12
          minLength: 1
          type: string
          description: |-
            Transaction amount in PKR, up to 2 
            decimal places
          examples:
            - '000000100000'
        TransmissionDateAndTime:
          maxLength: 10
          minLength: 1
          type: string
          description: |-
            Transmission date and time, Format: 
            “MMDDhhmmss”.
          examples:
            - '0715133513'
        STAN:
          maxLength: 6
          minLength: 1
          type: string
          description: |
            System Trace Audit Number.
          examples:
            - '102050'
        Time:
          maxLength: 6
          minLength: 1
          type: string
          description: |-
            Local transaction time,
            Format: “hhmmss”
          examples:
            - '133513'
        Date:
          maxLength: 4
          minLength: 1
          type: string
          description: ' Local transaction date. Format: “MMDD”'
          examples:
            - '0715'
        MerchantType:
          maxLength: 4
          minLength: 1
          type: string
          description: Four-digit code identifying merchant.
          examples:
            - '0003'
        FromBankIMD:
          maxLength: 11
          minLength: 1
          type: string
          description: The bank IMD/BIN of acquiring bank.
          examples:
            - '998876'
        RRN:
          maxLength: 12
          minLength: 1
          type: string
          description: Reference number sent by the acquirer.
          examples:
            - '000000024420'
        CardAcceptorTerminalId:
          maxLength: 8
          minLength: 1
          type: string
          description: Unique requesting terminal identifier.
          examples:
            - '40260275'
        CardAcceptorIdCode:
          maxLength: 15
          minLength: 1
          type: string
          description: Code uniquely identifying card acceptor.
          examples:
            - '402626030259047'
        MerchantDetail:
          maxLength: 999
          type: string
          description: In transactions this field contains Merchant Category code
          examples:
            - ''
        PaymentDetail:
          maxLength: 44
          minLength: 1
          type: string
          description: |-
            Issuing transactions this field contains Merchant Category code 
                      Payment Code (length=4) 
                      Payment Details (length=40)
          examples:
            - '0320 Donations  Charity                     '
        CurrencyCodeTransaction:
          maxLength: 3
          minLength: 1
          type: string
          description: 'Currency Code, Transaction is the local currency of the acquirer.'
          examples:
            - '586'
        AccountNumberFrom:
          maxLength: 28
          minLength: 1
          type: string
          description: >-
            AccountNumberFrom is a digits/characters used to identify customer
            account
          examples:
            - '3528555323354910'
        AccountNumberTo:
          maxLength: 28
          minLength: 1
          type: string
          description: This field contains Destination Account Number
          examples:
            - '6304532132598659'
        ToBankIMD:
          maxLength: 11
          minLength: 1
          type: string
          description: The bank IMD/BIN of issuer bank
          examples:
            - '221166'
        PAN:
          maxLength: 19
          type: string
          description: Personal Account Number.
          examples:
            - '4250108749566'
        ExpiryDate:
          maxLength: 4
          minLength: 1
          type: string
          examples:
            - '2205'
        PosEntMode:
          maxLength: 3
          minLength: 1
          type: string
          description: Point-of-Service Entry Mode
          examples:
            - '000'
        BeneficiaryBankName:
          maxLength: 20
          type: string
          description: This field will contain the Bank Name of “To/Destination” Account
          examples:
            - 1Link Model Bank
        Reserved1:
          maxLength: 999
          type: string
          examples:
            - Reserved for future
        Reserved2:
          maxLength: 999
          type: string
          examples:
            - Reserved for future
        Reserved3:
          maxLength: 1001
          type: string
          examples:
            - Reserved for future
      additionalProperties: false
    titleFetchRep:
      type: object
      properties:
        ResponseCode:
          type: string
        Pan:
          type: string
        Amount:
          type: string
        TransmissionDateAndTime:
          type: string
        Stan:
          type: string
        TimeLocalTransaction:
          type: string
        DateLocalTransaction:
          type: string
        DateSettlement:
          type: string
        RetrievalReferenceNumber:
          type: string
        AuthorizationIdentificationResponse:
          type: string
        accountNumberTo:
          type: string
        Alias:
          type: string
        ToBankImd:
          type: string
        accountTitleTo:
          type: string
        branchNameTo:
          type: string
        BankName:
          type: string
        IBAN_MobileAccountNumber:
          type: string
        Reserved1:
          type: string
        Reserved2:
          type: string
        Reserved3:
          type: string
        ResponseDetail:
          type: string
      additionalProperties: false